const rockAndMountainNames = [
    "Black Mountain",
    "Half Dome",
    "Sawmill Mountain",
    "Chironico North",
    "Silver Peak",
    "Dragon's Tooth",
    "Crimson Crag",
    "Whispering Pines Peak",
    "Eagle's Nest",
    "Mystic Mesa",
    "Cascade Cliffs",
    "Thunderhead Summit",
    "Quartz Quarry",
    "Mossy Monolith",
    "Sunset Spire",
    "Majestic Moraine",
    "Owl's Roost",
    "Cobalt Crest",
    "Rising Mist Rock",
    "Cedar Ridge",
    "Ironclad Peak",
    "Emerald Enclave",
    "Golden Gatestone",
    "Avalanche Ascent",
    "Jade Jut",
    "Copper Canyon",
    "Silent Sentinel",
    "Boulder Brook Bluff",
    "Dusky Divide",
    "Ruby Rampart",
    "Zephyr Zenith",
    "Marble Marauder",
    "Opal Outcrop",
    "Echoing Escarpment",
    "Frostbite Face",
    "Amber Apex",
    "Lunar Ledge",
    "Rustic Ridge",
    "Crimson Climb",
    "Granite Gorge",
    "Enchanted Edifice",
    "Starry Summit",
    "Molten Monolith",
    "Ivory Incline",
    "Obsidian Overlook",
    "Sapphire Spire",
    "Verdant Vista",
    "Whirlwind Wall",
    "Coral Crux",
    "Eternal Echo Cliff",
    "Amethyst Ascent",
    "Pinnacle Pass",
    "Crimson Peak",
    "Stormy Summit",
    "Quicksilver Quarry",
    "Cobalt Crest",
    "Rising Mist Rock",
    "Verdant Valley",
    "Granite Gateway",
    "Silverstone Slope",
    "Obsidian Oasis",
    "Golden Glade",
    "Azure Apex",
    "Whispering Willow Wall",
    "Moonlit Mesa",
    "Jade Jawbone",
    "Serenity Spire",
    "Thunderhead Terrace",
    "Flaming Forge",
    "Emerald Escarpment",
    "Majestic Mound",
    "Ruby Ridge",
    "Duskfall Dome",
    "Sapphire Shelf",
    "Iron Iris",
    "Mystic Marble",
    "Whirlpool Wall",
    "Ivory Isle",
    "Amber Anvil",
    "Crystal Chasm",
    "Windy Wilderness",
    "Molten Mirage",
    "Shadow Stone",
    "Copper Crest",
    "Lush Ledge",
    "Crimson Canyon",
    "Cascading Cliffs",
    "Stormy Spire",
    "Aurora Ascent",
    "Silent Summit",
    "Obsidian Outpost",
    "Eagle's Eyrie",
    "Celestial Crag",
    "Diamond Dome",
    "Terra Tower",
    "Veridian Vista",
    "Lunar Labyrinth",
    "Mossy Monolith",
    "Whispering Willow Wall",
    "Black Mountain",
    "Half Dome",
    "Sawmill Mountain",
    "Chironico North",
    "Silver Peak",
    "Dragon's Tooth",
    "Crimson Crag",
    "Whispering Pines Peak",
    "Eagle's Nest",
    "Mystic Mesa",
    "Cascade Cliffs",
    "Thunderhead Summit",
    "Quartz Quarry",
    "Mossy Monolith",
    "Sunset Spire",
    "Majestic Moraine",
    "Owl's Roost",
    "Cobalt Crest",
    "Rising Mist Rock",
    "Cedar Ridge",
    "Ironclad Peak",
    "Emerald Enclave",
    "Golden Gatestone",
    "Avalanche Ascent",
    "Jade Jut",
    "Copper Canyon",
    "Silent Sentinel",
    "Boulder Brook Bluff",
    "Dusky Divide",
    "Ruby Rampart",
    "Zephyr Zenith",
    "Marble Marauder",
    "Opal Outcrop",
    "Echoing Escarpment",
    "Frostbite Face",
    "Amber Apex",
    "Lunar Ledge",
    "Rustic Ridge",
    "Crimson Climb",
    "Granite Gorge",
    "Enchanted Edifice",
    "Starry Summit",
    "Molten Monolith",
    "Ivory Incline",
    "Obsidian Overlook",
    "Sapphire Spire",
    "Verdant Vista",
    "Whirlwind Wall",
    "Coral Crux",
    "Eternal Echo Cliff",
    "Amethyst Ascent",
    "Pinnacle Pass",
    "Crimson Peak",
    "Stormy Summit",
    "Quicksilver Quarry",
    "Cobalt Crest",
    "Rising Mist Rock",
    "Verdant Valley",
    "Granite Gateway",
    "Silverstone Slope",
    "Obsidian Oasis",
    "Golden Glade",
    "Azure Apex",
    "Whispering Willow Wall",
    "Moonlit Mesa",
    "Jade Jawbone",
    "Serenity Spire",
    "Thunderhead Terrace",
    "Flaming Forge",
    "Emerald Escarpment",
    "Majestic Mound",
    "Ruby Ridge",
    "Duskfall Dome",
    "Sapphire Shelf",
    "Iron Iris",
    "Mystic Marble",
    "Whirlpool Wall",
    "Ivory Isle",
    "Amber Anvil",
    "Crystal Chasm",
    "Windy Wilderness",
    "Molten Mirage",
    "Shadow Stone",
    "Copper Crest",
    "Lush Ledge",
    "Crimson Canyon",
    "Cascading Cliffs",
    "Stormy Spire",
    "Aurora Ascent",
    "Silent Summit",
    "Obsidian Outpost",
    "Eagle's Eyrie",
    "Celestial Crag",
    "Diamond Dome",
    "Terra Tower",
    "Veridian Vista",
    "Lunar Labyrinth",
    "Mossy Monolith",
    "Whispering Willow Wall",
    "Alpine Arch",
    "Frostfire Fortress",
    "Blazing Bluff",
    "Thunderstrike Summit",
    "Vivid Valley",
    "Rogue's Roost",
    "Sapphire Sentinel",
    "Whispering Windwall",
    "Eternal Echo Cliff",
    "Amethyst Ascent",
    "Pinnacle Pass",
    "Crimson Peak",
    "Stormy Summit",
    "Quicksilver Quarry",
    "Cobalt Crest",
    "Rising Mist Rock",
    "Verdant Valley",
    "Granite Gateway",
    "Silverstone Slope",
    "Obsidian Oasis",
    "Golden Glade",
    "Azure Apex",
    "Whispering Willow Wall",
    "Moonlit Mesa",
    "Jade Jawbone",
    "Serenity Spire",
    "Thunderhead Terrace",
    "Flaming Forge",
    "Emerald Escarpment",
    "Majestic Mound",
    "Ruby Ridge",
    "Duskfall Dome",
    "Sapphire Shelf",
    "Iron Iris",
    "Mystic Marble",
    "Whirlpool Wall",
    "Ivory Isle",
    "Amber Anvil",
    "Crystal Chasm",
    "Windy Wilderness",
    "Molten Mirage",
    "Shadow Stone",
    "Copper Crest",
    "Lush Ledge",
    "Crimson Canyon",
    "Cascading Cliffs",
    "Stormy Spire",
    "Aurora Ascent",
    "Silent Summit",
    "Obsidian Outpost",
    "Eagle's Eyrie",
    "Celestial Crag",
    "Diamond Dome",
    "Terra Tower",
    "Veridian Vista",
    "Lunar Labyrinth",
    "Mossy Monolith",
    "Whispering Willow Wall",
    "Alpine Arch",
    "Frostfire Fortress",
    "Blazing Bluff",
    "Thunderstrike Summit",
    "Vivid Valley",
    "Rogue's Roost",
    "Sapphire Sentinel",
    "Whispering Windwall",
    "Ambergris Abutment",
    "Avalanche Asylum",
    "Birch Bark Bluff",
    "Crimson Cascade",
    "Diamondback Dome",
    "Ember Enigma",
    "Fjordwatch Fell",
    "Garnet Gorge",
    "Hallowed Heights",
    "Inferno Incline",
    "Jade Jewel Jut",
    "Kestrel's Keep",
    "Luminous Ledge",
    "Magma Monastery",
    "Nebula Nexus",
    "Obsidian Overhang",
    "Pine Peak",
    "Quartz Quarry",
    "Rising Sun Spire",
    "Sapphire Serenity",
    "Thunderbird Terrace",
    "Umbral Uplift",
    "Vermilion Vista",
    "Whispering Willow Wall",
    "Xenolith Xanadu",
    "Yawning Yucca Yurt",
    "Zephyr Zenith",
    "Abyssal Arch",
    "Borealis Bluff",
    "Cedar Citadel",
    "Dewdrop Dell",
    "Ebon Echo Elevation",
    "Frostbloom Fortress",
    "Golden Grove",
    "Harmony Heights",
    "Ivory Icon",
    "Jagged Jade",
    "Kaleidoscope Knob",
    "Lunar Lookout",
    "Molten Mirage",
    "Nebula Nook",
    "Opal Overlook",
    "Pebble Pinnacle",
    "Quicksilver Quarry",
    "Radiant Ridge",
    "Sapphire Summit",
    "Tranquil Turret",
    "Umbral Umbra",
    "Vivid Vortex",
    "Whispering Willow Wall",
    "Xenon Xanadu",
    "Yellow Yurt",
    "Zephyr Zenith"
];

console.log(rockAndMountainNames.length);

module.exports = rockAndMountainNames;





