const names = [
    'The Gunks',
    'Red River Gorge',
    'Smith Rock',
    'Joshua Tree',
    'Yosemite',
    'Rumney Rocks',
    'The New River Gorge',
    'The Red Wall',
    'The Black Abyss',
    'The Obed',
    'Illuminati',
    'The Creek of Hollows',
    'The Diamond Wall',
    'The Flatirons',
    'The Needles',
    'The Tetons and the Grand Teton',
    'The Winds',
    'The Sawtooths',
    'The Bugaboos',
    'The Cirque of the Towers',
    'The Cirque of the Unclimbables',
    'The Cirque of the Towers',
    "Granite Grotto",
    "Limestone Ledge",
    "Sandstone Summit",
    "Quartz Quarry",
    "Basalt Bluff",
    "Schist Slope",
    "Dolomite Dome",
    "Gneiss Gully",
    "Chert Cliff",
    "Slate Spire",
    "Marble Mesa",
    "Obsidian Overhang",
    "Conglomerate Canyon",
    "Andesite Arch",
    "Breccia Boulders",
    "Felsite Face",
    "Rhyolite Ridge",
    "Shale Scree",
    "Trachyte Tower",
    "Pumice Peak",
    "Gabbro Gorge",
    "Pyroxenite Pinnacle",
    "Syenite Summit",
    "Amphibolite Ascent",
    "Peridotite Precipice",
    "Eclogite Escarpment",
    "Garnet Gully",
    "Jade Jut",
    "Jasper Jump",
    "Lapis Lazuli Ledge"
];


const locations = [
    { location: "Kalymnos Island", country: "Greece", latitude: 36.9585, longitude: 27.2877 },
    { location: "Krabi", country: "Thailand", latitude: 8.0863, longitude: 98.9063 },
    { location: "El Chorro", country: "Spain", latitude: 36.9081, longitude: 4.7728 },
    { location: "Squamish", country: "Canada", latitude: 49.7016, longitude: 123.1550 },
    { location: "Fontainebleau", country: "France", latitude: 48.4047, longitude: 2.7016 },
    { location: "Joshua Tree National Park", state: 'California', country: "USA", latitude: 33.8734, longitude: 115.9010 },
    { location: "Railay", country: "Thailand", latitude: 8.0121, longitude: 98.8378 },
    { location: "Bishop", state: 'California', country: "USA", latitude: 37.3614, longitude: 118.3997 },
    { location: "Meteora", country: "Greece", latitude: 39.7139, longitude: 21.6308 },
    { location: "Zion National Park", state: 'Washingon', country: "USA", latitude: 37.2982, longitude: 113.0263 },
    { location: "Arco", country: "Italy", latitude: 45.9186, longitude: 10.8858 },
    { location: "Ceuse", country: "France", latitude: 44.5272, longitude: 5.9417 },
    { location: "Hueco Tanks", state: 'Arizona', country: "USA", latitude: 31.9129, longitude: 106.0465 },
    { location: "Siurana", country: "Spain", latitude: 41.2653, longitude: 0.9326 },
    { location: "Red Rocks", state: 'Nevada', country: "USA", latitude: 36.1350, longitude: 115.4272 },
    { location: "Frankenjura", country: "Germany", latitude: 49.7594, longitude: 11.3128 },
    { location: "Boven", country: "South Africa", latitude: 25.6701, longitude: 27.2423 },
    { location: "Geyikbayiri", country: "Turkey", latitude: 36.9789, longitude: 30.5067 },
    { location: "Chulilla", country: "Spain", latitude: 39.6667, longitude: 0.9167 },
    { location: "Rumney", state: 'New York', country: "USA", latitude: 43.8670, longitude: 71.7979 },
    { location: "Margalef", country: "Spain", latitude: 41.2833, longitude: 0.7667 },
    { location: "Sella", country: "Spain", latitude: 38.6500, longitude: 0.1500 },
    { location: "Oliana", country: "Spain", latitude: 42.0500, longitude: 1.3000 },
    { location: "Todra Gorge", country: "Morocco", latitude: 31.5083, longitude: 5.5986 },
    { location: "Rodellar", country: "Spain", latitude: 42.2333, longitude: 0.0167 },
    { location: "Kalymnos", country: "Greece", latitude: 36.9585, longitude: 27.2877 },
    { location: "Yangshuo", country: "China", latitude: 24.7833, longitude: 110.4833 },
    { location: "Tonsai", country: "Thailand", latitude: 8.0121, longitude: 98.8378 },
    { location: "Squamish", country: "Canada", latitude: 49.7016, longitude: 123.1550 },
    { location: "Fontainebleau", country: "France", latitude: 48.4047, longitude: 2.7016 }
];


module.exports = { names, locations };
